"""Add friend column

Revision ID: 8039ae73dd15
Revises: 1d13f6ab4ee1
Create Date: 2024-07-24 21:16:56.486356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8039ae73dd15'
down_revision: Union[str, None] = '1d13f6ab4ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('friends', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'friends')
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
