"""Add n column

Revision ID: 9298454c695c
Revises: bc20b23e16ed
Create Date: 2024-06-05 16:22:16.474929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9298454c695c'
down_revision: Union[str, None] = 'bc20b23e16ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('n', sa.Integer(), autoincrement=True, nullable=True))
    op.create_unique_constraint(None, 'users', ['n'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'n')
    # ### end Alembic commands ###
