"""Remove TIMESTAMP field

Revision ID: e3c1ff41ddc4
Revises: b53ec3bdf34f
Create Date: 2024-07-30 10:33:51.982680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c1ff41ddc4'
down_revision: Union[str, None] = 'b53ec3bdf34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user1', sa.VARCHAR(), nullable=True),
    sa.Column('user2', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user1'),
    sa.UniqueConstraint('user2')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat', sa.INTEGER(), nullable=True),
    sa.Column('user', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###
